
package com.player.ui.view;

import com.player.core.ports.AudioPlayerInterface;
public class MainPlayerView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainPlayerView.class.getName());
    private final AudioPlayerInterface reproductor = new com.player.infrastructure.audio.JavaSoundPlayerAdapter();
    private String rutaCancionActual = "/com/player/resources/music/despacito_espanol.mp3";
    private java.util.List<String> filaCanciones = new java.util.ArrayList<>();
    private int indiceActual = 0;
    private boolean cancionEnPausa = false;
    private javax.swing.Timer reproductorTimer;
    private int segundosTranscurridos = 0;
    private javax.swing.Timer timerProgreso;
    
    
    public MainPlayerView() {
        initComponents();
        actualizarFilaDeReproduccion("Español");
        
        // Registrar el evento del ratón en la barra de progreso
        sldProgreso.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                // 1. Obtenemos el valor numérico en segundos
                int nuevoSegundo = sldProgreso.getValue();
                
                // 2. Sincronizamos el contador de tiempo interno
                segundosTranscurridos = nuevoSegundo;
                
                // 3. Calculamos el porcentaje proporcional
                double porcentaje = (nuevoSegundo / (double) sldProgreso.getMaximum()) * 100.0;
                
                // 4. Actualizamos visualmente las etiquetas de tiempo (mm:ss)
                int minutos = segundosTranscurridos / 60;
                int segundos = segundosTranscurridos % 60;
                lblTiempoActual.setText(String.format("%02d:%02d", minutos, segundos));
                
                // 5. Enviamos la orden al adaptador de audio
                if (reproductor != null) {
                    reproductor.seek(porcentaje);
                }
            }
        }); // Cierre correcto del addMouseListener
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPortada = new javax.swing.JLabel();
        cmbIdiomaTono = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblTituloCancion = new javax.swing.JLabel();
        lblTiempoActual = new javax.swing.JLabel();
        sldProgreso = new javax.swing.JSlider();
        lblTiempoTotal = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sldVolumen = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(24, 25, 28));

        lblPortada.setBackground(new java.awt.Color(40, 42, 54));
        lblPortada.setOpaque(true);

        cmbIdiomaTono.setBackground(new java.awt.Color(55, 58, 74));
        cmbIdiomaTono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbIdiomaTono.setForeground(new java.awt.Color(255, 255, 255));
        cmbIdiomaTono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Inglés", "Tono Minion", " " }));
        cmbIdiomaTono.addActionListener(this::cmbIdiomaTonoActionPerformed);

        lblTituloCancion.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloCancion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTituloCancion.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloCancion.setText("Titulo");

        lblTiempoActual.setBackground(new java.awt.Color(255, 255, 255));
        lblTiempoActual.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTiempoActual.setForeground(new java.awt.Color(255, 255, 255));
        lblTiempoActual.setText("00:00");

        sldProgreso.setBackground(new java.awt.Color(90, 94, 115));
        sldProgreso.setForeground(new java.awt.Color(40, 167, 69));
        sldProgreso.setValue(0);
        sldProgreso.addPropertyChangeListener(this::sldProgresoPropertyChange);

        lblTiempoTotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTiempoTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTiempoTotal.setText("00:00");

        btnAnterior.setBackground(new java.awt.Color(38, 113, 66));
        btnAnterior.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnAnterior.setText("Prev");
        btnAnterior.setOpaque(true);
        btnAnterior.addActionListener(this::btnAnteriorActionPerformed);

        btnStart.setBackground(new java.awt.Color(38, 113, 66));
        btnStart.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("Start");
        btnStart.addActionListener(this::btnStartActionPerformed);

        btnPause.setBackground(new java.awt.Color(38, 113, 66));
        btnPause.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPause.setForeground(new java.awt.Color(255, 255, 255));
        btnPause.setText("Pause");
        btnPause.addActionListener(this::btnPauseActionPerformed);

        btnStop.setBackground(new java.awt.Color(38, 113, 66));
        btnStop.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnStop.setForeground(new java.awt.Color(255, 255, 255));
        btnStop.setText("Stop");
        btnStop.addActionListener(this::btnStopActionPerformed);

        btnNext.setBackground(new java.awt.Color(38, 113, 66));
        btnNext.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Next");
        btnNext.addActionListener(this::btnNextActionPerformed);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("+");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("-");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Volumen");

        sldVolumen.addChangeListener(this::sldVolumenStateChanged);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTituloCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPortada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNext))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTiempoActual)
                                .addGap(12, 12, 12)
                                .addComponent(sldProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTiempoTotal))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sldVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(cmbIdiomaTono, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblTituloCancion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(sldVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbIdiomaTono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiempoActual)
                    .addComponent(sldProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiempoTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnStart)
                        .addComponent(btnPause)
                        .addComponent(btnStop)
                        .addComponent(btnNext)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldProgresoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sldProgresoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_sldProgresoPropertyChange
 
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if (!filaCanciones.isEmpty()) {
            cancionEnPausa = false;
            btnPause.setText("Pause"); // Aseguramos que el botón de pausa vuelva a su estado normal
            
            segundosTranscurridos = 0;
            sldProgreso.setValue(0);
            
            reproducirSeleccionada(); // Arranca desde el principio
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        if (reproductor != null && !filaCanciones.isEmpty()) {
            if (!cancionEnPausa) {
                // ⏸️ ACCIÓN: PAUSAR
                cancionEnPausa = true;
                reproductor.pause(); // Le avisa al adaptador que detenga la línea física
                
                if (reproductorTimer != null) {
                    reproductorTimer.stop(); // Congela el reloj visual en el segundo exacto
                }
                btnPause.setText("Play");
            } else {
                // ▶️ ACCIÓN: DESPAUSAR
                cancionEnPausa = false;
                reproductor.resume(); // Reanuda exactamente en el mismo bit sin alterar el flujo
                
                if (reproductorTimer != null) {
                    reproductorTimer.start(); // El segundero continúa avanzando
                }
                btnPause.setText("Pause");
            }
        }
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        reproductor.stop();
        cancionEnPausa = false;
        if (reproductorTimer != null) {
            reproductorTimer.stop(); // Apaga el temporizador
        }
        segundosTranscurridos = 0;
        sldProgreso.setValue(0); // Regresa la barra a 0
        lblTiempoActual.setText("00:00"); // Limpia el texto de tiempo
    }//GEN-LAST:event_btnStopActionPerformed

    private void cmbIdiomaTonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIdiomaTonoActionPerformed
        String opcion = cmbIdiomaTono.getSelectedItem().toString();
        actualizarFilaDeReproduccion(opcion);
    }//GEN-LAST:event_cmbIdiomaTonoActionPerformed

    private void sldVolumenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVolumenStateChanged
        float floatVolumen = sldVolumen.getValue() / 100.0f;
        
        // 1. Intentamos avisar al adaptador de software
        if (reproductor != null) {
            reproductor.setVolume(floatVolumen);
        }
        
        // Forzar los decibelios directamente en los altavoces de la PC
        try {
            for (javax.sound.sampled.Mixer.Info mixerInfo : javax.sound.sampled.AudioSystem.getMixerInfo()) {
                javax.sound.sampled.Mixer mixer = javax.sound.sampled.AudioSystem.getMixer(mixerInfo);
                for (javax.sound.sampled.Line line : mixer.getSourceLines()) {
                    if (line.isOpen() && line.isControlSupported(javax.sound.sampled.FloatControl.Type.MASTER_GAIN)) {
                        javax.sound.sampled.FloatControl gainControl = 
                            (javax.sound.sampled.FloatControl) line.getControl(javax.sound.sampled.FloatControl.Type.MASTER_GAIN);
                        
                        // Conversión logarítmica exacta de porcentaje (0.0 a 1.0) a Decibelios (dB)
                        float dB = (float) (Math.log(floatVolumen == 0 ? 0.0001 : floatVolumen) / Math.log(10.0) * 20.0);
                        if (dB < -80.0f) dB = -80.0f;
                        if (dB > 6.0f) dB = 6.0f;
                        
                        gainControl.setValue(dB);
                    }
                }
            }
        } catch (Exception e) {
            // Previene errores si el canal del sistema operativo se encuentra ocupado
        }
    }//GEN-LAST:event_sldVolumenStateChanged
    
    
    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if (!filaCanciones.isEmpty()) {
            cancionEnPausa = false;
            
            // Forzar apagado total previo antes del cambio
            reproductor.stop();
            if (reproductorTimer != null) { reproductorTimer.stop(); }
            if (timerProgreso != null) { timerProgreso.stop(); }
            
            indiceActual = (indiceActual - 1 + filaCanciones.size()) % filaCanciones.size();
            actualizarInterfazTitulo();
            reproducirSeleccionada();
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (!filaCanciones.isEmpty()) {
            cancionEnPausa = false;
            
            // Forzar apagado total previo antes del cambio
            reproductor.stop();
            if (reproductorTimer != null) { reproductorTimer.stop(); }
            if (timerProgreso != null) { timerProgreso.stop(); }
            
            indiceActual = (indiceActual + 1) % filaCanciones.size();
            actualizarInterfazTitulo();
            reproducirSeleccionada();
        }
    }//GEN-LAST:event_btnNextActionPerformed
    
    private void actualizarFilaDeReproduccion(String filtro) {
        filaCanciones.clear();
        
        // El catálogo con todos tus archivos reales detectados por la consola
        String[] catalogoTodo = {
            "despacito_espanol.mp3.mp3",
            "despacito_ingles.mp3.mp3",
            "happy_espanol.mp3.mp3",
            "happy_ingles.mp3.mp3",
            "letitgo_ingles.mp3.wav",
            "libresoy_espanol.mp3.mp3",
            "subeme_espanol.mp3.mp3",
            "subeme_ingles.mp3.mp3",
            "waka_espanol.mp3.wav",
            "waka_ingles.mp3.wav"
        };
        
        // Definimos la marca del idioma a buscar
        String marcaIdioma = (filtro.equals("Inglés")) ? "_ingles" : "_espanol";
        
        // Si eligen Minion, usamos las pistas en español de base
        if (filtro.equals("Tono Minion")) {
            marcaIdioma = "_espanol"; 
        }

        // Agregamos a la fila cualquier archivo que contenga la marca del idioma elegido
        for (String cancion : catalogoTodo) {
            if (cancion.contains(marcaIdioma)) {
                filaCanciones.add("/com/player/resources/music/" + cancion);
            }
        }
        
        indiceActual = 0;
        actualizarInterfazTitulo();
    }
    
   // --- MainPlayerView.java ---

private void actualizarInterfazTitulo() {
    if (!filaCanciones.isEmpty()) {
        String rutaCompleta = filaCanciones.get(indiceActual);
        
        // Extraemos el nombre del archivo (ej: "despacito_espanol.mp3.mp3")
        String nombreArchivo = rutaCompleta.substring(rutaCompleta.lastIndexOf("/") + 1);
        
        // CORRECCIÓN: Buscamos dónde empieza el guion bajo "_" para sacar el nombre limpio de la canción
        String nombreCancionSinExtension = nombreArchivo;
        if (nombreArchivo.contains("_")) {
            nombreCancionSinExtension = nombreArchivo.substring(0, nombreArchivo.indexOf("_"));
        }
        
        // Actualizamos el Label de texto
        lblTituloCancion.setText("Sona: " + nombreCancionSinExtension + " (" + cmbIdiomaTono.getSelectedItem().toString() + ")");
        
        // Cargar Portada con el nombre limpio (ej: "despacito", "waka", "subeme")
        cargarPortada(nombreCancionSinExtension);
    }
}

private void cargarPortada(String nombreImagenBase) {
    try {
        //Si es letitgo O SI ES libresoy, la imagen real es frozen
        if (nombreImagenBase.toLowerCase().contains("letitgo") || nombreImagenBase.toLowerCase().contains("libresoy")) {
            nombreImagenBase = "frozen";
        }
        
        String rutaAbsolutaImagen = "C:/DivergentMusicPlayer/src/main/java/com/player/resources/images/" + nombreImagenBase + ".jpg.jpg";
        java.io.File archivoImagen = new java.io.File(rutaAbsolutaImagen);
        
        if (archivoImagen.exists()) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(archivoImagen.getAbsolutePath());
            java.awt.Image image = icon.getImage();
            java.awt.Image newimg = image.getScaledInstance(lblPortada.getWidth(), lblPortada.getHeight(), java.awt.Image.SCALE_SMOOTH);
            
            lblPortada.setIcon(new javax.swing.ImageIcon(newimg));
            lblPortada.repaint();
        } else {
            lblPortada.setIcon(null);
            System.err.println("❌ No se encontró la carátula en: " + rutaAbsolutaImagen);
        }
    } catch (Exception e) {
        System.err.println("Error cargando la interfaz de portada: " + e.getMessage());
    }
}

    private void reproducirSeleccionada() {
       if (!filaCanciones.isEmpty()) {
            // 1. ANULAR DE INMEDIATO CUALQUIER TIMER QUE PUDIERA QUEDAR CORRIENDO
            if (reproductorTimer != null) {
                reproductorTimer.stop();
            }
            if (timerProgreso != null) {
                timerProgreso.stop();
            }

            // 2. 🔥 MATAR CUALQUIER HILO DE AUDIO ANTERIOR ABIERTO EN LA TARJETA DE SONIDO
            if (reproductor != null) {
                try {
                    reproductor.stop(); // Llamada obligada al adaptador
                } catch (Exception e) {
                    System.err.println("Aviso al detener adaptador: " + e.getMessage());
                }
            }

            // 3. Forzar el cierre de todas las líneas físicas del sistema para evitar solapamientos
            try {
                for (javax.sound.sampled.Mixer.Info mixerInfo : javax.sound.sampled.AudioSystem.getMixerInfo()) {
                    javax.sound.sampled.Mixer mixer = javax.sound.sampled.AudioSystem.getMixer(mixerInfo);
                    for (javax.sound.sampled.Line line : mixer.getSourceLines()) {
                        if (line instanceof javax.sound.sampled.SourceDataLine) {
                            // Convertimos la línea genérica a una línea de datos de audio real
                            javax.sound.sampled.SourceDataLine lineaDatos = (javax.sound.sampled.SourceDataLine) line;
                            lineaDatos.stop();
                            lineaDatos.flush();
                            lineaDatos.close(); // Borra por completo el búfer de la pista anterior
                        }
                    }
                }
            } catch (Exception e) {
                System.err.println("Error limpiando buffers nativos: " + e.getMessage());
            }

            // Resetear estados visuales si no es una reanudación de pausa
            if (!cancionEnPausa) {
                segundosTranscurridos = 0;
                sldProgreso.setValue(0);
                lblTiempoActual.setText("00:00");
            }

            String rutaInterna = filaCanciones.get(indiceActual);
            String nombreArchivo = rutaInterna.substring(rutaInterna.lastIndexOf("/") + 1);
            String rutaAbsolutaPC = "C:\\DivergentMusicPlayer\\src\\main\\java\\com\\player\\resources\\music\\" + nombreArchivo;
            
            String seleccion = cmbIdiomaTono.getSelectedItem().toString().trim();
            boolean esMinion = seleccion.equalsIgnoreCase("Tono Minion") || seleccion.equalsIgnoreCase("Tono Minión");
            
            java.io.File archivoFinal = new java.io.File(rutaAbsolutaPC);
            if (archivoFinal.exists()) {
                // Iniciar canal de audio fresco
                reproductor.play(rutaAbsolutaPC, 1.0, esMinion);
                
                // Sincronizar el volumen actual directamente con tu adaptador
                if (reproductor != null) {
                    float floatVolumen = sldVolumen.getValue() / 100.0f;
                    reproductor.setVolume(floatVolumen);
                }
                
                // Disparar el reloj visual único
                iniciarHbraProgreso();
                System.out.println("🎵 Reproduciendo pista limpia: " + nombreArchivo);
            }
        }
    }
    private void iniciarHbraProgreso() {
        if (reproductorTimer != null) {
            reproductorTimer.stop();
        }
        
        sldProgreso.setMaximum(180); // Duración estimada
        lblTiempoTotal.setText("03:00");

        reproductorTimer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (!cancionEnPausa) { 
                    segundosTranscurridos++;
                    sldProgreso.setValue(segundosTranscurridos);
                    
                    int minutos = segundosTranscurridos / 60;
                    int segundos = segundosTranscurridos % 60;
                    lblTiempoActual.setText(String.format("%02d:%02d", minutos, segundos));
                    
                    if (segundosTranscurridos >= sldProgreso.getMaximum()) {
                        reproductorTimer.stop();
                    }
                }
            }
        });
        reproductorTimer.start();
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainPlayerView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JComboBox<String> cmbIdiomaTono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPortada;
    private javax.swing.JLabel lblTiempoActual;
    private javax.swing.JLabel lblTiempoTotal;
    private javax.swing.JLabel lblTituloCancion;
    private javax.swing.JSlider sldProgreso;
    private javax.swing.JSlider sldVolumen;
    // End of variables declaration//GEN-END:variables
}
